services:
  api-gateway:
    container_name: dietician-api-gateway
    build:
      context: ./services/gateway
      dockerfile: deployments/dev/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./services/gateway:/app/services/gateway
      - ./packages:/app/packages

  account-service:
    container_name: dietician-account-service
    build:
      context: ./services/account-service
      dockerfile: deployments/dev/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./services/account-service:/app/services/account-service
      - ./packages:/app/packages

  recommendation-service:
    container_name: dietician-recommendation-service
    build:
      context: ./services/recommendation-service
      dockerfile: deployments/dev/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./services/recommendation-service:/app/services/recommendation-service
      - ./packages:/app/packages

  medical-service:
    container_name: dietician-medical-service
    build:
      context: ./services/medical-service
      dockerfile: deployments/dev/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./services/medical-service:/app/services/medical-service
      - ./packages:/app/packages

  progress-service:
    container_name: dietician-progress-service
    build:
      context: ./services/progress-service
      dockerfile: deployments/dev/Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./services/progress-service:/app/services/progress-service
      - ./packages:/app/packages