// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package progressservice

import (
	"dietician.local/services/progress-service/internal"
	"dietician.local/services/progress-service/internal/progress/handler"
	"dietician.local/services/progress-service/internal/progress/repository"
	"dietician.local/services/progress-service/internal/progress/service"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitRoute(db *sqlx.DB) internal.IRoute {
	iProgressRepository := repository.NewProgressRepository(db)
	iProgressService := service.NewProgressService(iProgressRepository)
	iProgressHandler := handler.NewProgressHandler(iProgressService)
	iRoute := internal.NewRoute(iProgressHandler)
	return iRoute
}

// wire.go:

var progressSet = wire.NewSet(repository.NewProgressRepository, service.NewProgressService, handler.NewProgressHandler)
