// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package recoservice

import (
	"dietician.local/packages/openai"
	"dietician.local/services/recommendation-service/config"
	"dietician.local/services/recommendation-service/internal"
	"dietician.local/services/recommendation-service/internal/recommendation/handler"
	"dietician.local/services/recommendation-service/internal/recommendation/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitRoute(cfg *config.RecommendationAppScheme, openaiService openai.Service) internal.IRoute {
	iRecommendationService := service.NewRecommendationService(openaiService)
	iRecommendationHandler := handler.NewRecommendationHandler(iRecommendationService)
	iRoute := internal.NewRoute(iRecommendationHandler)
	return iRoute
}

// wire.go:

var recoSet = wire.NewSet(service.NewRecommendationService, handler.NewRecommendationHandler)
