// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package medicalservice

import (
	"dietician.local/services/medical-service/config"
	"dietician.local/services/medical-service/internal"
	"dietician.local/services/medical-service/internal/medical/handler"
	"dietician.local/services/medical-service/internal/medical/repository"
	"dietician.local/services/medical-service/internal/medical/service"
	"dietician.local/services/medical-service/internal/storage"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitRoute(db *sqlx.DB, cfg *config.MedicalAppScheme, provider storage.Provider) internal.IRoute {
	iMedicalRepository := repository.NewMedicalRepository(db)
	iMedicalService := service.NewMedicalService(iMedicalRepository, provider)
	iMedicalHandler := handler.NewMedicalHandler(iMedicalService)
	iRoute := internal.NewRoute(iMedicalHandler)
	return iRoute
}

// wire.go:

var medicalSet = wire.NewSet(repository.NewMedicalRepository, service.NewMedicalService, handler.NewMedicalHandler)
