// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package medicalservice

import (
	"dietician.local/services/medical-service/config"
	"dietician.local/services/medical-service/internal"
	"dietician.local/services/medical-service/internal/storage"
	"dietician.local/services/medical-service/internal/uploads/handler"
	"dietician.local/services/medical-service/internal/uploads/orchestration"
	"dietician.local/services/medical-service/internal/uploads/repository"
	"dietician.local/services/medical-service/internal/uploads/service"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitRoute(db *sqlx.DB, cfg *config.MedicalAppScheme, provider storage.Provider, logger *logrus.Logger) internal.IRoute {
	iMedicalRepository := repository.NewMedicalRepository(db)
	iMedicalService := service.NewMedicalService(iMedicalRepository, provider, logger)
	iMedicalOrchestrator := orchestration.NewMedicalOrchestrator(iMedicalService)
	iMedicalHandler := handler.NewMedicalHandler(iMedicalOrchestrator)
	iRoute := internal.NewRoute(iMedicalHandler)
	return iRoute
}

// wire.go:

var medicalSet = wire.NewSet(repository.NewMedicalRepository, service.NewMedicalService, orchestration.NewMedicalOrchestrator, handler.NewMedicalHandler)
