root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
entrypoint = ["./tmp/main"]
include_ext = ["go", "toml"]
exclude_dir = ["tmp", "migrations"]
delay = 1000
kill_delay = 500
rerun = false

[log]
time = true

[misc]
clean_on_exit = true