// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package accountservice

import (
	"dietician.local/packages/tokenizer"
	"dietician.local/services/account-service/config"
	"dietician.local/services/account-service/internal"
	"dietician.local/services/account-service/internal/auth/handler"
	"dietician.local/services/account-service/internal/auth/orchestration"
	"dietician.local/services/account-service/internal/auth/repository"
	"dietician.local/services/account-service/internal/auth/service"
	handler2 "dietician.local/services/account-service/internal/profile/handler"
	orchestration2 "dietician.local/services/account-service/internal/profile/orchestration"
	repository2 "dietician.local/services/account-service/internal/profile/repository"
	service2 "dietician.local/services/account-service/internal/profile/service"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// InitializeRoute creates the main Route instance with all dependencies wired.
func InitRoute(db *sqlx.DB, cfg *config.AccountAppScheme, sender service.EmailSender, rdb *redis.Client, tok tokenizer.ITokenizer) internal.IRoute {
	iUserRepository := repository.NewUserRepository(db)
	iRefreshTokenRepo := repository.NewRefreshTokenRepository(db)
	iRefreshTokenService := service.NewRefreshTokenService(cfg, iRefreshTokenRepo, tok)
	iotpRepository := repository.NewOTPRepository(rdb)
	iotpService := service.NewOTPService(sender, cfg, iotpRepository)
	iUserService := service.NewUserService(iUserRepository, iRefreshTokenService, iotpService, tok)
	iAuthOrchestrator := orchestration.NewAuthOrchestrator(iUserService)
	iAuthHandler := handler.NewAuthHandler(iAuthOrchestrator)
	profileRepository := repository2.NewProfileRepository(db)
	profileService := service2.NewProfileService(profileRepository)
	iProfileOrchestrator := orchestration2.NewProfileOrchestrator(profileService)
	iProfileHandler := handler2.NewProfileHandler(iProfileOrchestrator)
	iRoute := internal.NewRoute(iAuthHandler, iProfileHandler)
	return iRoute
}

// wire.go:

// authSet wires authentication dependencies
var authSet = wire.NewSet(repository.NewUserRepository, repository.NewRefreshTokenRepository, repository.NewOTPRepository, service.NewOTPService, service.NewRefreshTokenService, service.NewUserService, orchestration.NewAuthOrchestrator, handler.NewAuthHandler)

// profileSet wires profile dependencies
var profileSet = wire.NewSet(repository2.NewProfileRepository, service2.NewProfileService, orchestration2.NewProfileOrchestrator, handler2.NewProfileHandler)
